sonyxperiadev/device-sony-nile

platform.mk
'soc.0' path has been replaced with 'soc' since k3.18.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> [master] Correct partitions paths for dm-verity configs

platform.mk
these are already set by common_props.mk
=> nile: remove duplicated audio props

platform.mk
* Fixes generating OTA packages:
AssertionError: cannot find vbmeta.img
=> Remove vbmeta from A/B partitions list

rootdir/vendor/etc/audio_platform_info.xml
we don't use NOIRQ which makes pcm fails and then not audio on specific audio usecases
=> audio: update low latency record pcm

rootdir/vendor/etc/audio_platform_info.xml
remove all unused SDN_DEVICE and USECASE_AUDIO not present in msm8974 audioHAL (aosp)
=> audio: cleanup audio_platform_info

rootdir/vendor/etc/fstab.nile
Remove firmware, bt_firmware, dsp and odm
partitions from the A/B update process
Signed-off-by: Dusan Beldedovski <dusan.beldedovski@sony.com>
=> [fstab] Remove partitions from A/B update

rootdir/vendor/etc/fstab.nile
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> [master] fstab: Update paths for k4.9

platform.mk
E: can't run /sbin/update_engine_sideload (No such file or directory)
=> build update_engine_sideload needed for flash OTA packages

sepolicy_platform/genfs_contexts
following CAF to avoid denials in health
01-24 13:53:30.894   646   646 I healthd : type=1400 audit(0.0:3): avc: denied { read } for name=type dev=sysfs ino=39053 scontext=u:r:healthd:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=1
01-24 13:53:30.894   646   646 I healthd : type=1400 audit(0.0:4): avc: denied { open } for path=/sys/devices/platform/soc/c176000.i2c/i2c-2/2-001d/power_supply/parallel/type dev=sysfs ino=39053 scontext=u:r:healthd:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=1
01-24 13:53:30.894   646   646 I healthd : type=1400 audit(0.0:5): avc: denied { getattr } for path=/sys/devices/platform/soc/c176000.i2c/i2c-2/2-001d/power_supply/parallel/type dev=sysfs ino=39053 scontext=u:r:healthd:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 …
=> label power_supply/parallel/type as sysfs_usb_supply

rootdir/vendor/etc/audio_platform_info.xml
Bit width and interface configurations are not supported in
platform_info.c
=> Bit width and interface not supported

rootdir/vendor/etc/audio_platform_info.xml
This reverts commit 854f580bb2a9191b86e6fe1342d37b11f3c6d048.
No sound, incorrect platform changes
Made a misstake and was working on both Pioneer and Akari at the same time and got the reference mixed up
=> Revert "audio_platform: Upate backends and interfaces"

rootdir/vendor/ueventd.rc, sepolicy_platform/genfs_contexts
On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
This branch for Android P+ and it uses kernel 4.9 only.
Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>
=> [master] Remove deprecated paths

rootdir/vendor/etc/wifi/wpa_supplicant_overlay.conf
Specify WoWLAN triggers to permit to keep the WiFi connected
while AP sleeps and the WLAN chip is in low power mode.
Resume the AP to handle special requests via a magic packet
sent from the WLAN chip.
=> [NILE] wifi: wpa_supplicant_overlay: Declare wowlan support

rootdir/vendor/etc/fstab.nile
Since there is no longer a command in init.common.rc that remounts as read-only, set the property directly in fstab.
=> [nile] fstab: Mount dsp partition read-only

sepolicy_platform/genfs_contexts
needed for Enforcing SELinux
discovery:/sys/class/backlight # ls -l
total 0
lrwxrwxrwx 1 root root 0 1970-05-10 03:18 panel0-backlight -> ../../devices/platform/soc/c900000.qcom,sde_kms/backlight/panel0-backlight
01-22 23:37:00.563   632   632 W light@2.0-servi: type=1400 audit(0.0:458): avc: denied { write } for name=brightness dev=sysfs ino=34255 scontext=u:r:hal_light_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
=> sepolicy: label SDE path as sysfs_leds

platform.mk
Set primary mixer stages to 1 to force getting no blend
support from the display HAL.
This switches us from the SDE composition to the GPU
composition, which is a hack that is required for legacy
platforms on the SDE driver because of a severe
incompatibility with the current blobs.
There are no barriers because the FBDEV driver-HAL
combo have no blobs to support the SDM composition
and this configuration is anyway already doing what we
are forcing there.
=> [NILE] platform: Disable SDE composition by forcing no blend

platform.mk
The `KERNEL_PATH` buildvar needs to be set before `common.mk` can be inherited.
=> [FIX] platform.mk: Define kernel vars before common.mk

rootdir/vendor/etc/fstab.nile
Based on https://github.com/sonyxperiadev/device-sony-yoshino/commit/59b75719fd133a9acb511f4e5b62fb719999573a
=> [master] fstab.nile: Enable adoptable storage

rootdir/vendor/ueventd.rc
On kernel 4.14 we've got a new driver for Tri-LED that adheres
...mostly... to the standard Linux way of dealing with LEDs.
Though, paths have changed!
=> [NILE] ueventd: Fix Tri-LED path permissions

overlay/frameworks/base/core/res/res/values/config.xml, platform.mk, rootdir/vendor/usr/idc/uinput-fpc.idc, rootdir/vendor/usr/keylayout/uinput-fpc.kl
For https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/50
These config files are used to tie uinput events coming from `uinput-fpc` to semantic names that are understood by Android.
=> [Nile] [4/7] Enable FPC gestures

rootdir/vendor/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini
Configure WCNSS to expose a secondary interface, wlan1, which is used
for concurrent AP while wlan0 runs the STA.
=> [NILE] WCNSS: Enable concurrent STA/AP on wlan1 interface.

platform.mk
See https://github.com/sonyxperiadev/device-sony-common/pull/667
The HAL used for kernel 4.14 (8.1 branch) exports allocator and mapper
v3. Setting this property makes sure the vintf manifest represents this,
in turn allowing the system to use it.
Tested on Discovery ROW.
TODO: We should see if all platforms are compatible with v3 (most likely every platform is, only Loire on fbdev might be tricky) and remove this opt-in altogether, or turn it into an opt-out for unsupported platforms.
=> [NILE] platform: Enable graphics allocator and mapper v3.

platform.mk, rootdir/vendor/etc/audio_policy_configuration.xml, rootdir/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml, rootdir/vendor/etc/common_primary_audio_policy_configuration.xml
The audio.bluetooth.default.so audio module, configured by
bluetooth_audio_policy_configuration.xml, utilizes the new HAL-based
mechanism to register a BT audio endpoint and transfer audio data.
Update our policy to route audio properly to this module, while
retaining a2dp input compatibility through the old mechanism.
See the identical change in crosshatch:
https://android.googlesource.com/device/google/crosshatch/+/c05ccdbed6c7c74d450e7149969c6c3431155628
audio_policy_configuration_bluetooth_legacy_hal.xml remains unchanged to
reflect the old variant of the system (using sockets between the BT
stack and audioserver), usable with
persist.bluetooth.bluetooth_audio_hal.disabled=true.
NOTE: This relies on device-sony-common to add the new files to
PRODUCT_COPY_FILES.
=> [NILE] audio_policy: Migrate to bluetooth.audio@2.0 HAL policy

sepolicy_platform/genfs_contexts
sysfs_usb_supply is a custom file type serving the same purpose as
sysfs_batteryinfo from AOSP, which at the same time is already granted
read access to relevant domains such as hal_health_default.
Replace this property to normalize policy with other battery/power
related files.
=> [NILE] sepolicy_platform: Replace sysfs_usb_supply with sysfs_batteryinfo

rootdir/vendor/etc/fstab.nile
Makes things neater with the stage-separated mounting logic in Q and later.
=> [VERIFYME] fstab: Split into early and latemount, reserve 128M on /data

rootdir/vendor/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini
Update the configuration for new drivers, including the
enablement of roaming between 5 and 2.4GHz networks (where
previously only 2.4GHz to 5GHz roaming was working, not vice
versa), monitor the network SNR for faster roaming decision,
adaptive dwell, enable Tx beamforming in VHT20MHz and others.
Needs testing on new wifi driver.
=> [NILE] vendor: WCNSS_qcom_cfg: Update configuration for new drivers

platform.mk
The optimal offload buffer size is 64kb on SDM630/6.
=> platform: Set optimal audio offload buffer size

platform.mk
This feature is required because devices in this platform do not expose
an echo-reference-voip mixer path, where -voip is concatenated when this
feature is disabled. With this feature enabled echo-reference is
selected instead, which is available and solves broken voice calls in
certain apps.
=> [NILE] Enable audio compr_voip feature

rootdir/vendor/etc/init/init.nile.pwr.rc
in the 4.14 kernel these configs are deprecated and should be removed to get rid of irrelevant errors in dmesg/logcat.
=> init.nile.pwr.rc: remove deprecated configs

rootdir/vendor/ueventd.rc
Contains:
1. Update NFC device name.
2. Remove obsolete NFC device permissions.
3. Update RGB LED sysfs path.
=> [master] Ueventd updates for 4.19 kernel
